say:
  name: "Thông báo TTS EDGE AZURE"
  description: "Chuyển văn bản thành âm thanh và phát qua EDGE TTS"
  fields:
    entity_id:
      description: "ID của media player sẽ phát âm thanh"
      example: "media_player.living_room_speaker"
    message:
      description: "Nội dung tin nhắn sẽ chuyển thành âm thanh"
      example: "Xin chào, đây là thông báo từ EDGE TTS"
  author: "Vũ Tuyển"
